import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Happy Birthday Hafsa Mehak",
  description:
    "A romantic digital love letter celebrating Hafsa Mehak with soft gradients, heartfelt stories, and playful surprise.",
  themeColor: "#fdf3fb",
  icons: {
    icon: "/favicon.svg",
    apple: "/favicon.svg",
  },
  openGraph: {
    title: "Happy Birthday Hafsa Mehak",
    description:
      "A warm love letter in motion, whispering memories and surprise moments for Hafsa.",
    type: "website",
  },
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> a26392a (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
>>>>>>> a26392a (Initial commit from Create Next App)
        {children}
      </body>
    </html>
  );
}
